[project]
name = "langchain-tutorial"
version = "0.1.0"
description = "LangChain + Ollama setup using uv"
readme = "README.md"
requires-python = ">=3.10"

dependencies = [
    "langchain",
    "langchain-core",
    "langchain-community",
    "langchain-text-splitters",
    "langchain-ollama"
]

